name: Build Vaultwarden for FreeBSD AMD64

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Vaultwarden
      uses: actions/checkout@v4

    - name: Build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 14.1
        prepare: |
          pkg update
          pkg install -y wget curl git gcc bash gawk gsed pkgconf openssl sqlite3 mysql80-client ca_root_nss
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          ln -sf /usr/lib/libssl.so.30 /usr/local/lib/libssl.so.12
          ln -sf /usr/lib/libcrypto.so.30 /usr/local/lib/libcrypto.so.12
        run: |
          . "$HOME/.cargo/env"
          cargo --version
          export LATEST_APP=$(wget -qO- https://api.github.com/repos/dani-garcia/vaultwarden/tags | gawk -F '["v]' '/name/{print $4;exit}')
          git clone -b $LATEST_APP https://github.com/dani-garcia/vaultwarden
          cd vaultwarden
          cargo build --features sqlite --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: vaultwarden-freebsd-amd64
        path: vaultwarden/target/release/vaultwarden

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/dani-garcia/vaultwarden/tags | gawk -F '["v]' '/name/{print $4;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              vaultwarden/target/release/vaultwarden

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
